package br.com.douglasoliveira10.javadraw.model;

import java.util.List;

/**
 * @param id         unique id: {@code owner#name(descriptor)}
 * @param signature  display signature, e.g. {@code place(Order order): Receipt}
 * @param accessor   trivial getter or setter
 * @param generated  generated by the compiler: enum {@code values/valueOf}, record {@code equals/hashCode/toString}
 * @param inherited  not declared in the owner; created because it is called through the owner type
 * @param entryPoint externally triggered method (HTTP handler, listener, scheduler, main)
 * @param endpoint   human readable trigger, e.g. {@code GET /orders/{id}}
 * @param line       first source line, or 0 when unknown
 */
public record MethodInfo(
        String id,
        String name,
        String descriptor,
        String signature,
        Visibility visibility,
        boolean isStatic,
        boolean isAbstract,
        boolean isConstructor,
        boolean accessor,
        boolean generated,
        boolean inherited,
        boolean entryPoint,
        String endpoint,
        List<AnnotationInfo> annotations,
        int line) {

    public MethodInfo withEntryPoint(String endpoint) {
        return new MethodInfo(id, name, descriptor, signature, visibility, isStatic, isAbstract, isConstructor,
                accessor, generated, inherited, true, endpoint, annotations, line);
    }
}
